default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  # don't do this in real app
  username: postgres
  password: postgres

development:
  <<: *default
  database: app_dev

test:
  <<: *default
  database: app_test